# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.rSVDdpd_cpp <- function(X, alpha, A, B, nd = NA_integer_, tol = 1e-4, eps = 1e-4, maxiter = 100L) {
    .Call(`_rsvddpd_rSVDdpd_cpp`, X, alpha, A, B, nd, tol, eps, maxiter)
}

